### ISSUE TITLE
How the Covid Certificate will be used?

### ISSUE THREAD

**Issue by gagarine** [admin-ch/CovidCertificate-Documents#10]
I understand it will be used to cross country borders inside EU. What are the other use cases?

Who can verify a code?
Why not everyone can verify a code?

**Comment by herpaderpaldent** [comment]
> Who can verify a code? 

Everyone

> Why not everyone can verify a code?

Well you can, either by using one of the Swiss Covid Certficate Check Apps or by building your own verification app. Or if you really feel like having it: you can do it by hand. You find all informations needed in the the documentation. Both the Swiss repos as well as the eu repos hold all necessairy informations. 

I linked you the two app repositories which contain the check app.
iOS: https://github.com/admin-ch/CovidCertificate-App-iOS#covid-certificate-check-app
Android: https://github.com/admin-ch/CovidCertificate-App-Android#covid-certificate-check-app

This is how it is mocked
![image](https://user-images.githubusercontent.com/6583519/120353353-e6d47900-c301-11eb-928a-2f06fddadf42.png)

**Comment by gagarine** [comment]
Thanks. I didn't understand the motivation for making two app (that can store **and** check). So I taught they may have limitation to who can access the "check app".
