### ISSUE TITLE
Übersetzungsproblem :CovidZertifikat_Presentation_System_Integration.pdf

### ISSUE THREAD

**Issue by mvidonne** [admin-ch/CovidCertificate-Documents#11]
Sprechende schalten Mikrofon ein  -> les personnes qui veulent parler allument leur microphone

Nichtsprechende schalten Videokamera und Mikrofon aus  -> les personnes qui ne veulent pas parler éteignent leur caméra et leur microphone

haut-parleurs= enceintes ->Lautsprecher

**Comment by cedricmoullet** [comment]
Merci ! On va adapter les slides !
