### ISSUE TITLE
EU certificate not accepted by the app due to invalid signature

### ISSUE THREAD

**Issue by silvianacmp** [admin-ch/CovidCertificate-Documents#26]
Hi,

I am trying to load an EU certificate in the Covid Cert app, as I have been vaccinated abroad but am a resident of Switzerland. My understanding is that the EU and Swiss certs should be interoperable. However, even though in Covid Cert I see all the vaccine data being read from the QR, the signature is marked as invalid.
Is this because the EU verification is not yet in place from a technical perspective or is there some legislation issue that prevents it from being accepted?
Or, is it the case that the EU QR will never be approved in Covid Cert/Covid Check? Which would be a worst case scenario considering that event entrance is strictly based on the Swiss Covid Cert.

Thanks.

**Comment by cedricmoullet** [comment]
The recognition process of the Swiss certificate by the EU is ongoing. During a six-week transition period (until August 12), it is expected that other certificates will also be accepted in the EU/EFTA area. It is strongly recommended to inform yourself about the current entry requirements in the destination country before traveling.
