### ISSUE TITLE
Copy/Paste

### ISSUE THREAD

**Issue by artnum** [admin-ch/CovidCertificate-Documents#6]
In the documentation you write that you will add support for copy/paste of data between application. Copy/paste is not a safe method of exchanging data, is there any sensitive data that will be exchanged this way ? In that case, is there any method to make it secure ?

**Comment by cedricmoullet** [comment]
Thanks for your comment. We are currently analyzing the best way to develop this function.

**Comment by artnum** [comment]
So no answer, no discussion ... what a strange "public test". More like someone said in another issue, this is "opensource washing".
